baseURL = 'http://example.org/'
copyright = "{year}"
theme = "lowkey"
title = 'Zac'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh'
enableRobotsTXT = true
summaryLength = 15
paginate = 5

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
