[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "关于"
    url = "/about"
    weight = 2

[[main]]
    identifier = "categories"
    name = "分类"
    url = "/categories"
    weight = 3
