isSinglePage = true

description = "代码 · 科技 · 折腾"

avatar = "img/profile-picture.jpg"

favicon = "icons/favicon.ico"

[social]
  github = "https://github.com/zhuzhuyule"
  twitter = "https://x.com/zhuzhuzacx"
  email = "mailto:blog@ause.cc"
  rss = true

disqusShortname = ""

[emoji]
  enableEmoji = true

[giscus]
  enable = false
  repo = ""
  repoId = ""
  category = "Announcements"
  categoryId = ""